spring.datasource.url=jdbc:postgresql://localhost:5432/palmery_manage_dev
spring.datasource.username=postgres
spring.datasource.password=law210

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

logging.level.id.ac.ui.cs.advprog.palmerymanage=DEBUG

